main: fr.xxathyx.chunkhoppers.Main
name: ChunkHoppers
version: 1.3
author: Xxathyx
description: ChunkHoppers
softdepend: [Vault]

commands:
  hoppers:
    description: "Chunk Hoppers main commands."
    usage: 
    permission: chunkhoppers.command.hoppers